WINDOW:
  RATIO_MARGIN_TO_WINDOW_HEIGHT: 40
  WIDTH: 4609
  HEIGHT: 2592
  MARGIN: 65
  COLOR:
    BACKGROUND: [255, 255, 255]

BOARD:
  DIMENSIONS:
    ROWS: 20
    COLS: 10
    ROWS_HIDDEN: 2
    ROWS_TOTAL: 22
  RECT:
    LEFT: 1760
    TOP: 130
    WIDTH: 1090
    HEIGHT: 2398
  COLOR:
    BACKGROUND: [55, 55, 55]
  CELL:
    WIDTH: 109
    HEIGHT: 109
  GRID_LINES:
    ENABLED: true
    LINE_COLOR: [180, 180, 180]
    LINE_WIDTH: 1

FIELDS:
  LINE_COUNTER:
    HEIGHT_CELLS: 2
    LEFT: 1760
    TOP: 65
    WIDTH: 1090
    HEIGHT: 218
  SCORE:
    HEIGHT_CELLS: 6
    WIDTH_CELLS: 8
    LEFT: 2915
    TOP: 65
    WIDTH: 872
    HEIGHT: 654
  NEXT:
    HEIGHT_CELLS: 4
    WIDTH_CELLS: 4
    LEFT: 2915
    TOP: 1111
    WIDTH: 436
    HEIGHT: 436
  LEVEL:
    HEIGHT_CELLS: 3
    WIDTH_CELLS: 5
    LEFT: 2915
    TOP: 1612
    WIDTH: 545
    HEIGHT: 327
  STATISTICS:
    HEIGHT_CELLS: 17
    WIDTH_CELLS: 9
    LEFT: 714
    TOP: 675
    WIDTH: 981
    HEIGHT: 1853
  TYPE:
    HEIGHT_CELLS: 2
    WIDTH_CELLS: 7
    LEFT: 823
    TOP: 174
    WIDTH: 763
    HEIGHT: 218

POLYOMINO:
  SIZE: 4
  COLOR: [200, 255, 200]
  ALL_SHAPES:
    - [[0, 0], [0, 1], [1, 1], [1, 2]]
    - [[0, 1], [1, 0], [1, 1], [1, 2]]
    - [[0, 0], [0, 1], [0, 2], [1, 0]]
    - [[0, 0], [1, 0], [1, 1], [1, 2]]
    - [[0, 0], [0, 1], [1, 0], [1, 1]]
    - [[0, 0], [0, 1], [0, 2], [0, 3]]
    - [[0, 0], [1, 0], [1, 1], [2, 1]]
  SPAWN_POSITION: [5, 2]
  SPAWN_POSITION_NEXT: [13, 3]

DIRECTIONS:
  UP: [0, -1]
  DOWN: [0, 1]
  LEFT: [-1, 0]
  RIGHT: [1, 0]
  ROTATE_CLOCKWISE: 1
  ROTATE_COUNTERCLOCKWISE: -1

DAS:
  DIRECTIONS: [LEFT, RIGHT, DOWN]
  DAS_DELAY_NTSC: 16
  DAS_DELAY_PAL: 12
  AUTO_REPEAT_RATE_NTSC: 6
  AUTO_REPEAT_RATE_PAL: 4

SCORE:
  SINGLE: 40
  DOUBLE_MULTIPLIER: 2.5
  TRIPLE_MULTIPLIER: 3.0
  TETRIS_MULTIPLIER: 4.0
  SOFT_DROP_PER_LINE: 1
  HARD_DROP_PER_LINE: 1

GENERAL:
  START_LEVEL: 0
  SOFT_DROP_SPEED: 0.5
  ARE_DELAY: 18
  NTSC_FRAMERATE: 60.0988
  PAL_FRAMERATE: 50.007
  NTSC_DROP_FRAMES:
    0: 48
    1: 43
    2: 38
    3: 33
    4: 28
    5: 23
    6: 18
    7: 13
    8: 8
    9: 6
    10: 5
    13: 4
    16: 3
    19: 2
    29: 1
  PAL_DROP_FRAMES:
    0: 36
    1: 32
    2: 29
    3: 25
    4: 22
    5: 18
    6: 15
    7: 11
    8: 7
    9: 5
    10: 4
    13: 3
    16: 2
    19: 1
