WINDOW:
  WIDTH: 1920
  HEIGHT: 1080
  COLOR:
    BACKGROUND: [255, 255, 255]

BOARD:
  DIMENSIONS:
    ROWS: 20
    COLS: 10
  RECT:
    LEFT: 740
    TOP: 40
    WIDTH: 500
    HEIGHT: 1000
  COLOR:
    BACKGROUND: [55, 55, 55]

POLYOMINO:
  SIZE: 2
  COLOR: [200, 255, 200]

DIRECTIONS:
  UP: [0, -1]
  DOWN: [0, 1]
  LEFT: [-1, 0]
  RIGHT: [1, 0]
  ROTATE_CLOCKWISE: 1
  ROTATE_COUNTERCLOCKWISE: -1
