WINDOW:
  WIDTH: 1920
  HEIGHT: 1080
  COLOR:
    BACKGROUND: [255, 255, 255]
BOARD:
  DIMENSIONS:
    ROWS: 20
    COLS: 10
  RECT:
    LEFT: 740
    TOP: 40
    WIDTH: 500
    HEIGHT: 1000
  COLOR:
    BACKGROUND: [55, 55, 55]
  CELL:
    WIDTH: 50
    HEIGHT: 50
POLYOMINO:
  COLOR: [200, 255, 200]
  SIZE: 6
  ALL_SHAPES:
    - [[0, 1], [0, 2], [0, 3], [0, 4], [1, 0], [1, 1]]
    - [[0, 0], [0, 1], [1, 0], [1, 1], [1, 2], [1, 3]]
    - [[0, 1], [1, 1], [2, 0], [2, 1], [2, 2], [3, 2]]
    - [[0, 1], [1, 0], [1, 1], [1, 2], [2, 0], [3, 0]]
    - [[0, 0], [1, 0], [2, 0], [2, 1], [2, 2], [2, 3]]
    - [[0, 0], [1, 0], [1, 1], [2, 1], [2, 2], [3, 2]]
    - [[0, 0], [0, 1], [1, 0], [2, 0], [2, 1], [2, 2]]
    - [[0, 1], [1, 1], [2, 1], [3, 0], [3, 1], [3, 2]]
    - [[0, 1], [1, 0], [1, 1], [1, 2], [2, 2], [2, 3]]
    - [[0, 2], [0, 3], [1, 0], [1, 1], [1, 2], [1, 3]]
    - [[0, 2], [1, 0], [1, 1], [1, 2], [1, 3], [2, 3]]
    - [[0, 1], [1, 0], [1, 1], [1, 2], [1, 3], [2, 2]]
    - [[0, 0], [1, 0], [1, 1], [1, 2], [1, 3], [1, 4]]
    - [[0, 0], [1, 0], [1, 1], [2, 0], [2, 1], [2, 2]]
    - [[0, 0], [0, 1], [1, 1], [1, 2], [1, 3], [1, 4]]
    - [[0, 3], [1, 0], [1, 1], [1, 2], [1, 3], [2, 0]]
    - [[0, 0], [0, 1], [1, 1], [2, 0], [2, 1], [2, 2]]
    - [[0, 1], [0, 2], [0, 3], [1, 0], [1, 1], [2, 0]]
    - [[0, 2], [1, 1], [1, 2], [1, 3], [2, 0], [2, 1]]
    - [[0, 1], [1, 0], [1, 1], [1, 2], [2, 2], [3, 2]]
    - [[0, 1], [1, 0], [1, 1], [1, 2], [1, 3], [2, 3]]
    - [[0, 0], [1, 0], [2, 0], [2, 1], [2, 2], [3, 2]]
    - [[0, 0], [0, 1], [1, 1], [1, 2], [2, 2], [2, 3]]
    - [[0, 0], [0, 1], [1, 0], [1, 1], [1, 2], [2, 1]]
    - [[0, 1], [0, 2], [1, 0], [1, 1], [1, 2], [2, 0]]
    - [[0, 3], [1, 0], [1, 1], [1, 2], [1, 3], [1, 4]]
    - [[0, 2], [1, 0], [1, 1], [1, 2], [1, 3], [2, 0]]
    - [[0, 0], [0, 1], [0, 2], [0, 3], [0, 4], [1, 0]]
    - [[0, 1], [0, 2], [1, 0], [1, 1], [1, 2], [1, 3]]
    - [[0, 1], [0, 3], [1, 0], [1, 1], [1, 2], [1, 3]]
    - [[0, 0], [0, 1], [1, 0], [1, 1], [1, 2], [2, 2]]
    - [[0, 1], [1, 0], [1, 1], [2, 0], [2, 1], [2, 2]]
    - [[0, 2], [1, 0], [1, 1], [1, 2], [1, 3], [2, 1]]
    - [[0, 0], [0, 2], [0, 3], [1, 0], [1, 1], [1, 2]]
    - [[0, 2], [0, 3], [0, 4], [1, 0], [1, 1], [1, 2]]
    - [[0, 0], [0, 1], [0, 2], [1, 1], [1, 2], [1, 3]]
    - [[0, 3], [1, 1], [1, 2], [1, 3], [2, 0], [2, 1]]
    - [[0, 1], [1, 0], [1, 1], [1, 2], [1, 3], [2, 0]]
    - [[0, 2], [1, 2], [2, 0], [2, 1], [2, 2], [2, 3]]
    - [[0, 0], [0, 1], [0, 2], [0, 3], [0, 4], [0, 5]]
    - [[0, 0], [0, 1], [0, 3], [1, 1], [1, 2], [1, 3]]
    - [[0, 1], [1, 1], [1, 2], [2, 0], [2, 1], [2, 2]]
    - [[0, 2], [1, 0], [1, 1], [1, 2], [1, 3], [1, 4]]
    - [[0, 0], [0, 1], [0, 2], [1, 0], [1, 1], [1, 2]]
    - [[0, 0], [1, 0], [1, 1], [1, 2], [1, 3], [2, 3]]
    - [[0, 1], [0, 2], [1, 1], [2, 0], [2, 1], [2, 2]]
    - [[0, 0], [0, 1], [1, 1], [1, 2], [1, 3], [2, 3]]
    - [[0, 1], [1, 1], [2, 0], [2, 1], [2, 2], [2, 3]]
    - [[0, 0], [1, 0], [1, 1], [2, 1], [2, 2], [2, 3]]
    - [[0, 0], [0, 2], [1, 0], [1, 1], [1, 2], [1, 3]]
    - [[0, 0], [0, 3], [1, 0], [1, 1], [1, 2], [1, 3]]
    - [[0, 0], [0, 1], [1, 1], [2, 1], [2, 2], [2, 3]]
    - [[0, 1], [1, 1], [2, 0], [2, 1], [2, 2], [3, 0]]
    - [[0, 1], [1, 0], [1, 1], [1, 2], [2, 0], [2, 2]]
    - [[0, 1], [1, 0], [1, 1], [1, 2], [1, 3], [1, 4]]
    - [[0, 0], [0, 1], [0, 2], [0, 3], [1, 0], [2, 0]]
    - [[0, 0], [1, 0], [1, 2], [2, 0], [2, 1], [2, 2]]
    - [[0, 1], [0, 2], [0, 3], [1, 0], [1, 1], [1, 2]]
    - [[0, 0], [0, 1], [0, 2], [1, 2], [1, 3], [1, 4]]
    - [[0, 1], [1, 1], [2, 0], [2, 1], [2, 2], [3, 1]]
DIRECTIONS:
  UP: [0, -1]
  DOWN: [0, 1]
  LEFT: [-1, 0]
  RIGHT: [1, 0]
  ROTATE_CLOCKWISE: 1
  ROTATE_COUNTERCLOCKWISE: -1
