WINDOW:
  WIDTH: 2270
  HEIGHT: 1620
  MARGIN: 50
  COLOR:
    BACKGROUND: [255, 255, 255]
BOARD:
  DIMENSIONS:
    ROWS: 25
    COLS: 12
    ROWS_HIDDEN: 4
    ROWS_TOTAL: 29
  RECT:
    LEFT: 820.5172413793103
    TOP: 50
    WIDTH: 628.9655172413793
    HEIGHT: 1520
  COLOR:
    BACKGROUND: [55, 55, 55]
  CELL:
    WIDTH: 52.41379310344828
    HEIGHT: 52.41379310344828
POLYOMINO:
  COLOR: [200, 255, 200]
  SIZE: 4
  ALL_SHAPES:
    - [[0, 0], [0, 1], [1, 1], [1, 2]]
    - [[0, 1], [1, 0], [1, 1], [1, 2]]
    - [[0, 0], [0, 1], [0, 2], [1, 0]]
    - [[0, 0], [1, 0], [1, 1], [1, 2]]
    - [[0, 0], [0, 1], [1, 0], [1, 1]]
    - [[0, 0], [0, 1], [0, 2], [0, 3]]
    - [[0, 0], [1, 0], [1, 1], [2, 1]]
DIRECTIONS:
  UP: [0, -1]
  DOWN: [0, 1]
  LEFT: [-1, 0]
  RIGHT: [1, 0]
  ROTATE_CLOCKWISE: 1
  ROTATE_COUNTERCLOCKWISE: -1
