WINDOW:
  WIDTH: 2270
  HEIGHT: 1620
  MARGIN: 50
  COLOR:
    BACKGROUND: [255, 255, 255]

BOARD:
  DIMENSIONS:
    ROWS: 20
    COLS: 10
    ROWS_HIDDEN: 2
  COLOR:
    BACKGROUND: [55, 55, 55]
  GRID_LINES:
    ENABLED: True
    LINE_COLOR: [180, 180, 180]
    LINE_WIDTH: 1

POLYOMINO:
  SIZE: 4
  COLOR: [200, 255, 200]

DIRECTIONS:
  UP: [0, -1]
  DOWN: [0, 1]
  LEFT: [-1, 0]
  RIGHT: [1, 0]
  ROTATE_CLOCKWISE: 1
  ROTATE_COUNTERCLOCKWISE: -1

DAS:
  DIRECTIONS: ["LEFT", "RIGHT", "DOWN"]
  DAS_DELAY_NTSC: 16
  DAS_DELAY_PAL: 12
  AUTO_REPEAT_RATE_NTSC: 6
  AUTO_REPEAT_RATE_PAL: 4

SCORE:
  SINGLE: 40
  DOUBLE_MULTIPLIER: 2.5 # A double is worth 2.5 times a single.
  TRIPLE_MULTIPLIER: 3 # A triple is worth 3 times a double.
  TETRIS_MULTIPLIER: 4 # A tetris is worth 4 times a triple.
  SOFT_DROP_PER_LINE: 1
  HARD_DROP_PER_LINE: 1

GENERAL:
  START_LEVEL: 18
  SOFT_DROP_SPEED: 0.5 # Units: Gravity. Definition of gravity: Gravity is expressed in unit G, where 1G = 1 cell per frame, and 0.1G = 1 cell per 10 frames
  ARE_DELAY: 18
  NTSC_FRAMERATE: 60.0988
  PAL_FRAMERATE: 50.0070
  NTSC_DROP_FRAMES:
    0: 48
    1: 43
    2: 38
    3: 33
    4: 28
    5: 23
    6: 18
    7: 13
    8: 8
    9: 6
    10: 5
    13: 4
    16: 3
    19: 2
    29: 1
  PAL_DROP_FRAMES:
    0: 36
    1: 32
    2: 29
    3: 25
    4: 22
    5: 18
    6: 15
    7: 11
    8: 7
    9: 5
    10: 4
    13: 3
    16: 2
    19: 1