BOARD:
  CELL:
    HEIGHT: 50
    WIDTH: 50
  COLOR:
    BACKGROUND: !!python/tuple
    - 55
    - 55
    - 55
  DIMENSIONS:
    COLS: 10
    ROWS: 20
  RECT:
    HEIGHT: 1000
    LEFT: 740
    TOP: 40
    WIDTH: 500
TETROMINO:
  COLOR: !!python/tuple
  - 200
  - 200
  - 200
  SIZE: 4
WINDOW:
  COLOR:
    BACKGROUND: !!python/tuple
    - 255
    - 255
    - 255
  HEIGHT: 1080
  WIDTH: 1920
