WINDOW:
  WIDTH: 2270
  HEIGHT: 1620
  COLOR:
    BACKGROUND: [255, 255, 255]
BOARD:
  DIMENSIONS:
    ROWS: 20
    COLS: 10
  RECT:
    LEFT: 760
    TOP: 60
    WIDTH: 750
    HEIGHT: 1500
  COLOR:
    BACKGROUND: [55, 55, 55]
  CELL:
    WIDTH: 75
    HEIGHT: 75
POLYOMINO:
  COLOR: [200, 255, 200]
  SIZE: 4
  ALL_SHAPES:
    - [[0, 0], [0, 1], [1, 1], [1, 2]]
    - [[0, 1], [1, 0], [1, 1], [1, 2]]
    - [[0, 0], [0, 1], [0, 2], [1, 0]]
    - [[0, 0], [1, 0], [1, 1], [1, 2]]
    - [[0, 0], [0, 1], [1, 0], [1, 1]]
    - [[0, 0], [0, 1], [0, 2], [0, 3]]
    - [[0, 0], [1, 0], [1, 1], [2, 1]]
DIRECTIONS:
  UP: [0, -1]
  DOWN: [0, 1]
  LEFT: [-1, 0]
  RIGHT: [1, 0]
  ROTATE_CLOCKWISE: 1
  ROTATE_COUNTERCLOCKWISE: -1
