BOARD:
  CELL:
    HEIGHT: 50
    WIDTH: 50
  COLOR:
    BACKGROUND: [55, 55, 55]
  DIMENSIONS:
    COLS: 10
    ROWS: 20
  RECT:
    HEIGHT: 1000
    LEFT: 740
    TOP: 40
    WIDTH: 500
DIRECTIONS:
  DOWN: [1, 0]
  LEFT: [0, -1]
  RIGHT: [0, 1]
  ROTATE_CLOCKWISE: 1
  ROTATE_COUNTERCLOCKWISE: -1
  UP: [-1, 0]
POLYOMINO:
  ALL_SHAPES: []
  COLOR: [200, 255, 200]
  SIZE: 4
WINDOW:
  COLOR:
    BACKGROUND: [255, 255, 255]
  HEIGHT: 1080
  WIDTH: 1920
