BOARD:
  CELL:
    HEIGHT: 50
    WIDTH: 50
  COLOR:
    BACKGROUND: [55, 55, 55]
  DIMENSIONS:
    COLS: 10
    ROWS: 20
  RECT:
    HEIGHT: 1000
    LEFT: 740
    TOP: 40
    WIDTH: 500
POLYOMINO:
  ALL_SHAPES: [[[0, 0], [1, 0], [2, 0], [3, 0]], [[0, 0], [0, 1], [1, 1], [1, 2]],
    [[0, 0], [0, 1], [1, 1], [2, 1]], [[0, 1], [1, 0], [1, 1], [2, 1]], [[0, 0], [
        0, 1], [1, 0], [2, 0]], [[0, 0], [0, 1], [1, 0], [1, 1]], [[0, 0], [1, 0],
      [1, 1], [2, 1]]]
  COLOR: [200, 255, 200]
  SIZE: 4
WINDOW:
  COLOR:
    BACKGROUND: [255, 255, 255]
  HEIGHT: 1080
  WIDTH: 1920
