WINDOW:
  WIDTH: 2270
  HEIGHT: 1620
  MARGIN: 50
  COLOR:
    BACKGROUND: [255, 255, 255]
BOARD:
  DIMENSIONS:
    ROWS: 20
    COLS: 10
    ROWS_HIDDEN: 2
    ROWS_TOTAL: 22
  RECT:
    LEFT: 789.5454545454545
    TOP: 50
    WIDTH: 690.9090909090909
    HEIGHT: 1520
  COLOR:
    BACKGROUND: [55, 55, 55]
  CELL:
    WIDTH: 69.0909090909091
    HEIGHT: 69.0909090909091
  GRID_LINES:
    ENABLED: true
    LINE_COLOR: [180, 180, 180]
    LINE_WIDTH: 1
POLYOMINO:
  COLOR: [200, 255, 200]
  SIZE: 4
  ALL_SHAPES:
    - [[0, 0], [0, 1], [1, 1], [1, 2]]
    - [[0, 1], [1, 0], [1, 1], [1, 2]]
    - [[0, 0], [0, 1], [0, 2], [1, 0]]
    - [[0, 0], [1, 0], [1, 1], [1, 2]]
    - [[0, 0], [0, 1], [1, 0], [1, 1]]
    - [[0, 0], [0, 1], [0, 2], [0, 3]]
    - [[0, 0], [1, 0], [1, 1], [2, 1]]
DIRECTIONS:
  UP: [0, -1]
  DOWN: [0, 1]
  LEFT: [-1, 0]
  RIGHT: [1, 0]
  ROTATE_CLOCKWISE: 1
  ROTATE_COUNTERCLOCKWISE: -1
